#!/usr/bin/env bash
set -euo pipefail

TARGET_WAVE="${1:-12}"
OUTPUT_PATH="${2:-tmp/autoplay-record-wave-${TARGET_WAVE}.md}"
TEST_BUILD="${3:-${LOVE_AUTOPLAY_TEST_BUILD:-}}"
START_WAVE="${4:-${LOVE_AUTOPLAY_START_WAVE:-}}"
SPEED="${LOVE_AUTOPLAY_SPEED:-12}"
WINDOW_W="${LOVE_WINDOW_W:-1280}"
WINDOW_H="${LOVE_WINDOW_H:-720}"
TIMEOUT_SECONDS="${LOVE_AUTOPLAY_TIMEOUT:-180}"
MAX_SIM_SECONDS="${LOVE_AUTOPLAY_MAX_SIM_SECONDS:-180}"

mkdir -p "$(dirname "$OUTPUT_PATH")"
rm -f "$OUTPUT_PATH"

runner=(love .)
if command -v xvfb-run >/dev/null 2>&1; then
  runner=(xvfb-run -a love .)
fi

LOVE_AUTOPLAY_RECORD=1 \
LOVE_AUTOPLAY_TARGET_WAVE="$TARGET_WAVE" \
LOVE_AUTOPLAY_TEST_BUILD="$TEST_BUILD" \
LOVE_AUTOPLAY_START_WAVE="$START_WAVE" \
LOVE_AUTOPLAY_SPEED="$SPEED" \
LOVE_AUTOPLAY_RECORD_PATH="$OUTPUT_PATH" \
LOVE_AUTOPLAY_MAX_SIM_SECONDS="$MAX_SIM_SECONDS" \
LOVE_WINDOW_W="$WINDOW_W" \
LOVE_WINDOW_H="$WINDOW_H" \
timeout "$TIMEOUT_SECONDS" "${runner[@]}"

printf 'autoplay_record=%s\n' "$OUTPUT_PATH"
